### ISSUE TITLE
Console flooding

### ISSUE THREAD

**Issue by Wyrrrd** [Corbris/FactorioChatBot#4]
This floods a lot of messages to console when not able to connect to the server

Is there a possibility to lower the frequency of connection checks, maybe to once a minute?

(Storytime: I was running it under Debian and wrapped it in a systemd unit. This causes the console messages being redirected to a log file, which itself causes the remaining disk space to shrink rapidly. The file grew to 40GB in minutes, only being stopped by the disk being full.)

**Comment by KevinTLucas** [comment]
fixed https://github.com/Corbris/FactorioChatBot/releases/tag/1.1.0

added option in the config for logging
