### ISSUE TITLE
Quotation Marks Aren't Sanitized

### ISSUE THREAD

**Issue by ghost** [Corbris/FactorioChatBot#5]
When quotation marks come into the discord chat, factorio responds with `Cannot execute command. Error: (command):1: ')' expected near '[whatever was in quotes]'`

This probably could enable anyone on a discord server to execute a command with admin privileges.

**Comment by KevinTLucas** [comment]
Fixed https://github.com/Corbris/FactorioChatBot/releases/tag/1.1.0
