### ISSUE TITLE
Discord @ tags and # channel names are bridged as the internal ID of the user or channel.

### ISSUE THREAD

**Issue by ghost** [Corbris/FactorioChatBot#6]
The title says it, mostly. If you @mention someone in Discord, their username is replaced with <@![ID]> in factorio's chat, and if you #mention a channel, the same happens with <#[ID]>.

**Comment by KevinTLucas** [comment]
Fixed https://github.com/Corbris/FactorioChatBot/releases/tag/1.1.0
