### ISSUE TITLE
Discord to ingame chat

### ISSUE THREAD

**Issue by szentigrad3** [Corbris/FactorioChatBot#7]
1st time i used discord to ingame chat i get this > 2020-04-08 16:52:26 [WARNING] Player <server> tried using a command "game.print("[Discord] Szentigrade: hey")"
2020-04-08 16:52:26 [WARNING] Using Lua console commands will disable achievements, please repeat the command to proceed

if there is another way of doing this without disabling achievements please do so

**Comment by AGuyNamedJens** [comment]
I know i'm kinda late, but i've made one, similar to this chatbot without disabling achievements, and without needing mods https://github.com/AGuyNamedJens/FactorioChatBot
